# Generated by Django 4.2.16 on 2024-09-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(
                choices=[("full time", "full time"), ("part time", "part time")],
                max_length=100,
            ),
        ),
    ]
