# Generated by Django 4.2.16 on 2024-09-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_alter_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[("full time", "full time"), ("part time", "part time")],
                default="",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
