# Generated by Django 4.2.16 on 2024-09-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0003_job_job_type_alter_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
